FROM bbaaxx/sd15db-runpod:latest 
ADD https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors /workspace/local_ckpts/v1-5-pruned-emaonly.safetensors

CMD [ "/start.sh" ]